<?php
/**
 * @file
 * csas quick form
 */

function csas_qf_form($form, &$form_state) {
  $css_m_file = _csas_qf_get_css_m_file('csas_qf.css');
  $form['#attached']['js'][] = drupal_get_path('module', 'csas_qf') . '/js/csas_qf.js';
  $form['#attached']['css'][] = $css_m_file;
  $form['#attributes']['class'] = 'css-qf-frm';
  $form['nme'] = array(
    '#type' => 'textfield',
    '#title' => t('Name'),
    '#required' => TRUE,
  );

  $form['pne'] = array(
    '#type' => 'textfield',
    '#title' => t('Phone'),
    '#required' => TRUE,
    '#attributes' => array('class' => array('csas-phn-msk'))
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );
  return $form;
}

function _csas_qf_get_css_m_file($fle = '') {
  global $theme;
  $pth = drupal_get_path('theme', $theme);
  $dta = $pth . '/css/' . $theme . '.' . $fle;
  if (file_exists($dta)) {
    return $dta;
  }
  else {
    $pth = drupal_get_path('module', 'csas_qf');
    return $pth . "/css/{$fle}";
  }
}

function csas_qf_form_validate($form, &$form_state) {
}

function csas_qf_form_submit($form, &$form_state) {
  csas_qf_mail_send($form_state['values']);
}

function csas_qf_mail_send($form_values) {
  global $language;
  $ru = $language->language == 'ru';
  $module = 'csas_qf';
  $key = 'ntf';
  $to = variable_get('csas_qf_mls', variable_get('site_mail', 'admin@example.com'));

  $urs = array();
  $rls = array_filter(variable_get('csas_qf_mls', array()));
  if (empty($rls)) {
    $rls[] = 'administrator';
  }

  $sel = db_select('users', 'u')
    ->fields('u', array('uid'))
    ->condition('u.status', 1);
  $sel->innerJoin('users_roles', 'ur', "ur.uid = u.uid");
  $sel->innerJoin('role', 'r', "r.rid = ur.rid AND r.rid IN('" . implode("','", $rls) . "')");

  $uid = $sel->execute()->fetchCol();

  if (!empty($uid)) {
    $urs = user_load_multiple($uid);
  }

  $from = variable_get('site_mail', 'admin@example.com');
  $params = $form_values;
  $language = language_default();
  $send = TRUE;
  $sent = FALSE;
  foreach ($urs as $urs_k => $urs_v) {
    $to = $urs_v->mail;
    $result = drupal_mail($module, $key, $to, $language, $params, $from, $send);
    $sent = $sent || $result['result'];
  }

  if ($sent) {
    $mes = $ru ? t('Спасибо, с Вами свяжутся.') : t('Your message has been sent.');
    drupal_set_message($mes);
  }
  else {
    $mes = $ru ? t('Попробуйте, пожалуйста, позже.') : t('There was a problem sending your message and it was not sent.');
    drupal_set_message($mes, 'error');
  }
}

function csas_qf_mail($key, &$message, $params) {
  global $user, $language;
  $ru = $language->language == 'ru';
  $options = array(
    'langcode' => $message['language']->language,
  );
  switch ($key) {
    case 'ntf':
      $sbj = $ru
        ? t('Обратный звонок с сайта @site-name', array('@site-name' => variable_get('site_name', 'Drupal')), $options)
        : t('Callback from @site-name', array('@site-name' => variable_get('site_name', 'Drupal')), $options);

      $message['subject'] = $sbj;
      //$message['body'][] = t('@name sent you the following message:', array('@name' => $user->name), $options);
      $message['body'][] = 'Имя: ' . check_plain($params['nme']);
      $message['body'][] = 'Телефон: ' . check_plain($params['pne']);
      break;
  }
}

/**
 * Implementation of hook_menu().
 */
function csas_qf_menu() {
  $items['admin/config/content/csas_qf'] = array(
    'title' => 'Csas quick form',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('csas_qf_admin_config_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'csas_qf.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function csas_qf_theme() {
  return array(
    'csas_qf_tme' => array(
      'variables' => array(
        'ots' => NULL,
      ),
      'file' => 'csas_qf.theme.inc',
    ),
  );
}